### ISSUE TITLE
Enhance the store tests mechanism

### ISSUE THREAD

**Issue by Pierregvx** [massalabs/station-store#29]
**Context**
as a dev when I want to list my plugin on the plugin store of massa station - this operation takes time and has few flaws in the tests : 
- it takes too much time to write the checksums
- the regex checks are to restrictive 
- some changes are not detected from one update of the store to another 
- we are not checking the manifest of the plugin

**User flow**
- create or update a plugin
- update or add a plugin in the `plugins.json`
- push & create a pr

**How to**
- [x] #19 
- [x] https://github.com/massalabs/station-store/pull/28  fix : detect all changes from one version of the store from the other
- [x]  https://github.com/massalabs/station-store/pull/34
- [x] https://github.com/massalabs/station-store/pull/33

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*
